### ISSUE TITLE
Image in the form is not showing

### ISSUE THREAD

**Issue by shravn1s** [Visionaryofthefuture/SE-TUT#1]
The image in the html form is not visible i believe that the Img tag is not able to locate the image file. i propose a solution of moving it to a folder same as the html file and then render it

**Comment by tejass-as** [comment]
Oh well..I'll look for it.

**Comment by tejass-as** [comment]
Done. Just check and let us know if there any other such problems

**Comment by Visionaryofthefuture** [comment]
ok Tejas, thank you for the issue being resolved, i will close this issue now
